logging:
  pattern:
    level: debug
server:
  port: 8093

spring:
  application:
    name: calculator-eureka-client-hystrix

eureka:
    client:
        register-with-eureka: true
        service-url:
            defaultZone: http://localhost:8761/eureka
 
